### ISSUE TITLE
Using norm instead of norm squared when calculating u_hat

### ISSUE THREAD

**Issue by VincentStimper** [tonyduan/normalizing-flows#2]
When calculating u_hat to ensure the invertibility of the planar flow Rezende & Mohamed divided w by its norm squared (see sec A.1 at p. 10 of [their article](https://arxiv.org/abs/1505.05770)). However, you are using the norm:
https://github.com/tonyduan/normalizing-flows/blob/d5e3d1d46ddc55f90342523277d338326d37c6b2/nf/flows.py#L53
This can lead to learned flows that cannot be inverted, contradicting the model assumptions. Hence, I recommend changing this.

**Comment by tonyduan** [comment]
Thanks for the notice -- really great catch! 

I just pushed a fix via [[this commit]](https://github.com/tonyduan/normalizing-flows/commit/a29bff4756d8306cd24515f2fb825763a71c3d90).

Let me know if anything else comes up!
