### ISSUE TITLE
GPU Usage

### ISSUE THREAD

**Issue by Baukebrenninkmeijer** [tonyduan/normalizing-flows#4]
Hi @tonyduan,

Great implementation. I was wondering, is this all easily used on the GPU as well? I'm trying some experiments, but some components do not seem to like it that much. For example, i'm not sure how to handle the normal distribution. 

Thanks!

**Comment by Baukebrenninkmeijer** [comment]
I got it working! If you're interested in the code, let me know.

**Comment by tonyduan** [comment]
Glad you figured it out!
