### ISSUE TITLE
Why widths and heights are not multiplied by 2B after softmax?

### ISSUE THREAD

**Issue by moonman925** [tonyduan/normalizing-flows#5]
https://github.com/tonyduan/normalizing-flows/blob/a29bff4756d8306cd24515f2fb825763a71c3d90/nf/utils.py#L71

Here I found this op on `widths` after softmax instead of multiplied by 2B, can you explain a bit for me what does this line of code mean please? Thx!

**Comment by tonyduan** [comment]
This line is making sure each width is at least `min_bin_width` wide (by default set to 1e-3).

The code here follows the [[implementation in the official repo for Neural Spline Flows]](https://github.com/bayesiains/nsf/blob/master/nde/transforms/splines/rational_quadratic.py#L74).

Hope this answers your question.
