### ISSUE TITLE
Request help for a flow model

### ISSUE THREAD

**Issue by mtsatsev** [tonyduan/normalizing-flows#9]
Hello, tonyduan. 
I want to perform inference of parameters of sin waves (phase, amplitude, frequency) based on 24 time steps so my data is of the form [batch_size,1,24] and I need to end up with [batch_size,1,3]. For that I want to make a network which can sample very fast, so I went for Inverse Autoregressive spline flow. I took parts of your code for inspiration, however I am stuck at some parts.
1. For example can the RQS function deal with input which has some input channels? 
2. How would you make the Inverse Autoregressive spline flow? Would you simply swap ```Inverse``` and ```forward``` or would you do it in a different way (for example how it is done in the paper but then without s_t and m_t but using splines)?

**Comment by tonyduan** [comment]
@mtsatsev Hi, sorry for the late reply. To try to answer:

1/ No it assumes scalar input.
2/ Yes that's how I'd approach it, though I haven't implemented the IAF myself. Open source implementations such as [[this one]](https://github.com/pclucas14/iaf-vae) may be a helpful reference.

Feel free to re-open if you have further questions.
